auto-sync repository files - Change the way to check vuln (#53)

diff --git a/.build/build.yaml b/.build/build.yaml
--- a/.build/build.yaml
+++ b/.build/build.yaml
@@ -159,7 +159,16 @@ spec:
 
             mkdir -p bin
             export VULNCHECK_OUTPUT=bin/vulncheck.txt
-            make vulncheck
+            # do not throw an error here immediately, but check whether it should fail in the subsequent logic
+            make vulncheck || true
+            # count means the line number which contains 'Fixed in' and has fix version
+            count=$(grep 'Fixed in' "$VULNCHECK_OUTPUT" | grep -v 'Fixed in: N/A' | wc -l)
+            if [ "$count" -gt 0 ]; then
+            echo "==> ❌ there are $count vulnerability need to be fixed"
+            exit 1
+            else
+            echo "==> ✅ there is no vulnerability need to be fixed"
+            fi
             # TODO: Add report back to PR
         - name: build-outputs-path
           value:
